version: '3.8'

services:
  frontend:
    build:
      context: ./affiliate-sites/affilio-client
    container_name: affilio-frontend 
    ports:
      - "80:80"  
    restart: unless-stopped

  app:
    build:
      context: ./backend/affilio
    container_name: affilio-backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/affilio/.env.docker  
    depends_on:
      - db
    volumes:
      - ./backend/affilio:/app  
      - /app/node_modules  
    command: ["sh", "-c", "cd /app && npx prisma migrate deploy && npx prisma generate && npm run dev"]
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./backend/affilio/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    restart: unless-stopped

volumes:
  postgres_data:



